/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package penjualan.kredit;

/**
 *
 * @author Hp
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama1
     */
    public MenuUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        mnProduk = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        mnTransaksi = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        mnAkun = new javax.swing.JMenu();
        mnManajemenAkun = new javax.swing.JMenuItem();
        mnManajemenHakAkses = new javax.swing.JMenuItem();
        mnHakPenggunaAkun = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penjualan/kredit/gambar/home.png"))); // NOI18N
        jMenu3.setText("File");
        jMenu3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu3.setMargin(new java.awt.Insets(10, 5, 5, 5));
        jMenu3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jMenuBar2.add(jMenu3);

        mnProduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penjualan/kredit/gambar/cart.png"))); // NOI18N
        mnProduk.setText("Produk");
        mnProduk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mnProduk.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mnProduk.setMargin(new java.awt.Insets(10, 5, 5, 5));
        mnProduk.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jMenuItem13.setText("Data Produk");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        mnProduk.add(jMenuItem13);

        jMenuItem14.setText("Data Kategori");
        mnProduk.add(jMenuItem14);

        jMenuItem15.setText("Data Merk");
        mnProduk.add(jMenuItem15);

        jMenuBar2.add(mnProduk);

        mnTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penjualan/kredit/gambar/change.png"))); // NOI18N
        mnTransaksi.setText("Transaksi");
        mnTransaksi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mnTransaksi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mnTransaksi.setMargin(new java.awt.Insets(10, 5, 5, 5));
        mnTransaksi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penjualan/kredit/gambar/credit-card.png"))); // NOI18N
        jMenuItem1.setText("Transaksi Kredit");
        mnTransaksi.add(jMenuItem1);

        jMenuItem2.setText("Pembayaran Kredit");
        mnTransaksi.add(jMenuItem2);

        jMenuBar2.add(mnTransaksi);

        mnAkun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penjualan/kredit/gambar/akun.png"))); // NOI18N
        mnAkun.setText("Akun");
        mnAkun.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mnAkun.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mnAkun.setMargin(new java.awt.Insets(10, 5, 5, 5));
        mnAkun.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        mnManajemenAkun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penjualan/kredit/gambar/users.png"))); // NOI18N
        mnManajemenAkun.setText("Manajemen Akun");
        mnManajemenAkun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnManajemenAkunActionPerformed(evt);
            }
        });
        mnAkun.add(mnManajemenAkun);

        mnManajemenHakAkses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penjualan/kredit/gambar/antivirus.png"))); // NOI18N
        mnManajemenHakAkses.setText("Manajemen Hak Akses");
        mnManajemenHakAkses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnManajemenHakAksesActionPerformed(evt);
            }
        });
        mnAkun.add(mnManajemenHakAkses);

        mnHakPenggunaAkun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penjualan/kredit/gambar/padlock.png"))); // NOI18N
        mnHakPenggunaAkun.setText("Hak Pengguna Akun");
        mnAkun.add(mnHakPenggunaAkun);

        jMenuBar2.add(mnAkun);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penjualan/kredit/gambar/notepad.png"))); // NOI18N
        jMenu5.setText("Laporan");
        jMenu5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu5.setMargin(new java.awt.Insets(10, 5, 5, 5));
        jMenu5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jMenuItem6.setText("Laporan Data Produk");
        jMenu5.add(jMenuItem6);

        jMenuItem7.setText("Laporan Data Transaksi");
        jMenu5.add(jMenuItem7);

        jMenuItem8.setText("Laporan Transaksi Kredit");
        jMenu5.add(jMenuItem8);

        jMenuItem9.setText("Laporan Data Retur Produk");
        jMenu5.add(jMenuItem9);

        jMenuBar2.add(jMenu5);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penjualan/kredit/gambar/pengaturan.png"))); // NOI18N
        jMenu6.setText("Pengaturan");
        jMenu6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu6.setMargin(new java.awt.Insets(10, 5, 5, 5));
        jMenu6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jMenu6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jMenuItem3.setText("Pengaturan Sistem");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem3);

        jMenuItem4.setText("Tentang Toko");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem4);

        jMenuItem5.setText("Tentang Aplikasi");
        jMenu6.add(jMenuItem5);

        jMenuBar2.add(jMenu6);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 564, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 233, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void mnManajemenAkunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnManajemenAkunActionPerformed
        boolean closable = true;
        ManajemenAkun manajemenAkun = new ManajemenAkun(null, closable);
        manajemenAkun.mu = this;
        manajemenAkun.setVisible(true);
    }//GEN-LAST:event_mnManajemenAkunActionPerformed

    private void mnManajemenHakAksesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnManajemenHakAksesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnManajemenHakAksesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenu mnAkun;
    private javax.swing.JMenuItem mnHakPenggunaAkun;
    private javax.swing.JMenuItem mnManajemenAkun;
    private javax.swing.JMenuItem mnManajemenHakAkses;
    private javax.swing.JMenu mnProduk;
    private javax.swing.JMenu mnTransaksi;
    // End of variables declaration//GEN-END:variables
}
